package rules
 
import br.edu.ufersa.multcare.persistence.entities.SistemaEspecialista;



rule "Todos os sintomas Hiperglicemia"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														nauseas=="S", 
														fadiga == "S", 
														fome =="S", 
														dorDeCabeca == "S", 
														visaoEmbacada == "S", 
														sonolencia == "S", 
														bocaSeca == "S",
														vontadeExcessivaUrinar == "S",
														dificuldadeRespirar == "S",
														halitoCetonico == "S",
														sedeExcessiva == "S"
													  ) 
	then
		sistemaEspecialistaObject.setTipoSintomas("Todos os sintomas Hiperglicemia");
		update(sistemaEspecialistaObject);
	end

rule "Alguns sintomas Hiperglicemia"
	when 
	
		sistemaEspecialistaObject: SistemaEspecialista(
														nauseas=="S", 
														fadiga == "S", 
														fome =="S", 
														dorDeCabeca == "S", 
														visaoEmbacada == "S", 
														sonolencia == "S", 
														bocaSeca == "F" ||
														vontadeExcessivaUrinar == "F" ||
														dificuldadeRespirar == "F" ||
														halitoCetonico == "F" ||
														sedeExcessiva == "F"
													 )  
	then
		sistemaEspecialistaObject.setTipoSintomas("Alguns sintomas Hiperglicemia");
		update(sistemaEspecialistaObject);
	end	
	

rule "Todos os sintomas Hipoglicemia"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														nauseas=="S", 
														fadiga == "S", 
														fome =="S", 
														dorDeCabeca == "S", 
														visaoEmbacada == "S", 
														sonolencia == "S",
														fraqueza == "S",
														confusaoMental == "S",
														tontura == "S",
														falaArrastada == "S",
														tremores == "S",														
														palpitacoes == "S",
														incPensarClaramente == "S",
														convulsoes == "S",
														suorExcessivo == "S"
													  ) 
	then
		sistemaEspecialistaObject.setTipoSintomas("Todos os sintomas Hipoglicemia");
		update(sistemaEspecialistaObject);
	end
		
rule "Alguns sintomas Hipoglicemia"
	when 
	
		sistemaEspecialistaObject: SistemaEspecialista(
														nauseas=="S", 
														fadiga == "S", 
														fome =="S", 
														dorDeCabeca == "S", 
														visaoEmbacada == "S", 
														sonolencia == "S",
														bocaSeca == "F",
														vontadeExcessivaUrinar == "F",
														dificuldadeRespirar == "F",
														halitoCetonico == "F",
														sedeExcessiva == "F",
														fraqueza == "F" ||
														confusaoMental == "F" ||
														tontura == "F" ||
														falaArrastada == "F" ||
														tremores == "F" ||														
														palpitacoes == "F" ||
														incPensarClaramente == "F" ||
														convulsoes == "F" ||
														suorExcessivo == "F"
													 )  
	then
		sistemaEspecialistaObject.setTipoSintomas("Alguns sintomas Hipoglicemia");
		update(sistemaEspecialistaObject);
	end	
	

rule "Todos os sintomas Hipocalemia"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														nauseas=="S",
														fraqueza == "S", 
														taquicardia =="S",  
														lesaoMuscular == "S",
														fadiga == "S",
														paralisia == "S",
														constipacao == "S",
														caimbra == "S"
													  ) 
	then
		sistemaEspecialistaObject.setTipoSintomas("Todos os sintomas Hipocalemia");
		update(sistemaEspecialistaObject);
	end
			

rule "Alguns sintomas Hipocalemia"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														nauseas=="S",
														fraqueza == "S", 
														taquicardia =="S",  
														lesaoMuscular == "S",
														fadiga == "F" ||
														paralisia == "F" ||
														constipacao == "F" ||
														caimbra == "F"
													  ) 
	then
		sistemaEspecialistaObject.setTipoSintomas("Alguns sintomas Hipocalemia");
		update(sistemaEspecialistaObject);
	end
				
		

rule "Todos os sintomas Hipercalemia"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														nauseas=="S", 
														fraqueza == "S", 
														taquicardia =="S", 														
														dorNoPeito == "S", 
														dormencia == "S",
														confusaoMental == "S",
														vomitos == "S",
														dificuldadeRespirar == "S"
													  ) 
	then
		sistemaEspecialistaObject.setTipoSintomas("Todos os sintomas Hipercalemia");
		update(sistemaEspecialistaObject);
	end
			
	

rule "Alguns sintomas Hipercalemia"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														nauseas=="S", 
														fraqueza == "S", 
														taquicardia =="S", 
														fadiga == "F",
														paralisia == "F",
														constipacao == "F",
														caimbra == "F",														
														dorNoPeito == "F" ||
														dormencia == "F" ||
														confusaoMental == "F" ||
														vomitos == "F" ||
														dificuldadeRespirar == "F"
													  ) 
	then
		sistemaEspecialistaObject.setTipoSintomas("Alguns sintomas Hipercalemia");
		update(sistemaEspecialistaObject);
	end
				
	
	

rule "medicamentos hiperglicemia"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														corticosteroides=="S" ||
														octreotida == "S" ||
														betabloqueadores =="S" || 
														epinefrina == "S" ||
														diureticosTiazidicos == "S" ||
														niacina == "S" ||
														pentamidina == "S" ||
														inibidoresDaProtease == "S" ||														
														lAsparaginase == "S" ||
														antipsicoticos == "S" ||
														olanzapina == "S" ||
														duloxetina == "S" ||
														antfetamina == "S" ||
														paroxetina == "S" ||
														pravastatina == "S"
													  ) 
	then
		sistemaEspecialistaObject.setMedicamentosHiperglicemia("S");
		update(sistemaEspecialistaObject);
	end
			
	

rule "medicamentos sulfmeg hipoglicemia"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														glibenclamida=="S" ||
														gliclazida == "S" ||
														glimepirida == "S" ||
														glipizida =="S" || 
														clorpropamida == "S" ||												
														nateglinida == "S" ||
														repaglinida == "S" 
														
													  ) 
	then
		sistemaEspecialistaObject.setMedicamentosSulfMegHipog("S");
		update(sistemaEspecialistaObject);
	end
				

rule "medicamentos hipoglicemia"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														acarbose == "S" ||
														metformina == "S" ||
														pioglitazona == "S" ||
														sitagliptina == "S" ||														
														vildagliptina == "S" ||
														saxagliptina == "S" ||
														exenatida == "S" 
														
													  ) 
	then
		sistemaEspecialistaObject.setMedicamentosHipoglicemia("S");
		update(sistemaEspecialistaObject);
	end
					
			

rule "medicamentos hipercalemia"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														espironolactona == "S" ||
														amilorida == "S" ||
														triantereno == "S" ||
														inibidoresDoECA == "S" ||
														antagonistaDosReceptoresDaAngiotensina == "S" ||
														antiInflamatoriosNaoEsteroides == "S" ||
														trimetoprim == "S" ||
														ciclosporina == "S" ||
														betabloqueadores == "S" ||
														penicilinaGPotassica == "S" 														
													  ) 
	then
		sistemaEspecialistaObject.setMedicamentosHipercalemia("S");
		update(sistemaEspecialistaObject);
	end													
														
														

rule "medicamentos hipocalemia"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														betaAgonista == "S" ||
														diureticosDeAlca == "S" ||
														diureticosTiazidicos == "S" ||
														albuterol == "S" ||
														terbutalina == "S" ||
														angiotensina == "S" 														
													  ) 
	then
		sistemaEspecialistaObject.setMedicamentosHipocalemia("S");
		update(sistemaEspecialistaObject);
	end													
														
				



rule "7: sintomas +diabetico +glicemia +resultado >200 = hiperglicemia 100% Hospital"
	when 
	
		sistemaEspecialistaObject: SistemaEspecialista(
		
														tipoSintomas == "Todos os sintomas Hiperglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia >= 200
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, Hospital");
	end
	
rule "8: sintomas +diabetico +glicemia -resultado >200 +medicamentos = hiperglicemia 75%"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hiperglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia < 200,
														medicamentosHiperglicemia == "S"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, UPA");
	end
 
 
rule "9: sintomas +diabetico +glicemia -resultado >200 -medicamentos = hiperglicemia 50% Hospital"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hiperglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia < 200,
														medicamentosHiperglicemia == "F"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, UPA");
	end
 
  
rule "10: sintomas +diabetico -glicemia +med = hiperglicemia 75% Hospital"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														
														tipoSintomas == "Todos os sintomas Hiperglicemia",
														diabetico =="S", 
														medirGlicemia == "F", 
														medicamentosHiperglicemia == "S"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, Hospital");
	end
 
   
rule "11: sintomas +diabetico -glicemia -med = hiperglicemia 50% Hospital"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														
														tipoSintomas == "Todos os sintomas Hiperglicemia",
														diabetico =="S", 
														medirGlicemia == "F", 
														medicamentosHiperglicemia == "F"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, Hospital");
	end
    
rule "12: sintomas -diabetico +glicose >= 126 = hiperglicemia 100%"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														
														tipoSintomas == "Todos os sintomas Hiperglicemia",
														diabetico =="F", 
														medirGlicemia == "S", 
														resultadoGlicemia >= 126
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, Hospital");
	end
 
     
rule "13: sintomas -diabetico +glicose ->=126 +med = hiperglicemia 50% UPA"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														
														tipoSintomas == "Todos os sintomas Hiperglicemia",
														diabetico =="F", 
														medirGlicemia == "S", 
														resultadoGlicemia < 126, 
														medicamentosHiperglicemia == "S"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, UPA");
	end
 
  
     
rule "14: sintomas -diabetico +glicose ->=126 -med = hiperglicemia 25% UPA"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														
														tipoSintomas == "Todos os sintomas Hiperglicemia",
														diabetico =="F", 
														medirGlicemia == "S", 
														resultadoGlicemia < 126,
														medicamentosHiperglicemia == "F"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, UPA");
	end
  
  
     
rule "15: sintomas -diabetico -glicose +med = hiperglicemia 50% upa"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														
														tipoSintomas == "Todos os sintomas Hiperglicemia",
														diabetico =="F", 
														medirGlicemia == "F", 
														medicamentosHiperglicemia == "S"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, Hospital");
	end
 
   
     
rule "16: sintomas -diabetico -glicose -med = hiperglicemia 25% UPA"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														
														tipoSintomas == "Todos os sintomas Hiperglicemia",
														diabetico =="F", 
														medirGlicemia == "F", 
														medicamentosHiperglicemia == "F"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, Hospital");
	end
      
rule "19: alguns sintomas +diabetico +glicose +glicemia >200 = hiperglicemia 100% HOSPITAL"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hiperglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia >= 200
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, HOSPITAL");
	end
       
       
rule "20: alguns sintomas +diabetico +glicose -glicemia >200 +med = hiperglicemia 63% UPA"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hiperglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia < 200,
														medicamentosHiperglicemia == "S"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, UPA");
	end
        
       
rule "21: alguns sintomas +diabetico +glicose -glicemia >200 -med = hiperglicemia 38% UPA"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hiperglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia < 200,
														medicamentosHiperglicemia == "F"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, UPA");
	end
        
rule "22: alguns sintomas +diabetico -glicose +med = hiperglicemia 63% UPA"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hiperglicemia",
														diabetico =="S", 
														medirGlicemia == "F",
														medicamentosHiperglicemia == "S"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, UPA");
	end
 
         
rule "23: alguns sintomas +diabetico -glicose -med= hiperglicemia 38% UPA"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hiperglicemia",
														diabetico =="S", 
														medirGlicemia == "F",
														medicamentosHiperglicemia == "F"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, UPA");
	end
 
          
rule "24: alguns sintomas -diabetico +glicose +glicemia >126 = hiperglicemia 100% UPA"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hiperglicemia",
														diabetico =="F", 
														medirGlicemia == "S",
														resultadoGlicemia >= 126
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, UPA");
	end
           
rule "25: alguns sintomas -diabetico +glicose +glicemia >126 +med = hiperglicemia 38% UPA"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hiperglicemia",
														diabetico =="F", 
														medirGlicemia == "S",
														resultadoGlicemia  < 126,
														medicamentosHiperglicemia == "S"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, UPA");
	end
            
rule "26: alguns sintomas -diabetico +glicose - glicemia >126 -med = hiperglicemia 13% UPA"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hiperglicemia",
														diabetico =="F", 
														medirGlicemia == "S",
														resultadoGlicemia < 126,
														medicamentosHiperglicemia == "F"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, UPA");
	end
 
             
rule "27: alguns sintomas -diabetico -glicemia +med = hiperglicemia 38% UPA"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hiperglicemia",
														diabetico =="F", 
														medirGlicemia == "F",
														medicamentosHiperglicemia == "S"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, UPA");
	end
              
rule "28: alguns sintomas -diabetico -glicemia +med = hiperglicemia 13% UPA"
	when     
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hiperglicemia",
														diabetico =="F", 
														medirGlicemia == "F",
														medicamentosHiperglicemia == "F"
													  ) 
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hiperglicemia, UPA");
	end
rule "34: sintomas +diabetico +glicose +glicemia <70 = hipoglicemia 100% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia <= 70
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, Hospital");
	end

 
rule "35: sintomas +diabetico +glicemia -resultado <70 +med sulf +insulina = hipoglicemia 80% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "S",
														insulina == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, Hospital");
	end
	
 
rule "36: sintomas +diabetico +glicemia -resultado <70 +med sulf -insulina +alcool = hipoglicemia 80% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "S",
														insulina == "F",
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");
	end
	
				
 
rule "37: sintomas +diabetico +glicemia -resultado <70 +med sulf -insulina -alcool = hipoglicemia 60% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "S",
														insulina == "F",
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");
	end
	
 
rule "38: sintomas +diabetico +glicemia -resultado <70 -med sulf +med +insulina = hipoglicemia 80% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "S",
														insulina == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");
	end
					

rule "39: sintomas +diabetico +glicemia -resultado <70 -med sulf +med -insulina +alcool = hipoglicemia 80% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "S",
														insulina == "F",
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");
	end
					
						

rule "40: sintomas +diabetico +glicemia -resultado <70 -med sulf +med -insulina -alcool = hipoglicemia 60% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "S",
														insulina == "F",
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");
	end
						

rule "41: sintomas +diabetico +glicemia -resultado <70 -med sulf +med -insulina -alcool = hipoglicemia 60% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "F",
														insulina == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");
	end
	
	
rule "42: sintomas +diabetico +glicemia -resultado <70 -med sulf +med -insulina -alcool = hipoglicemia 60% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "F",
														insulina == "F",
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");
	end
	
		
	
rule "43: sintomas +diabetico +glicemia -resultado <70 -med sulf -med -insulina -alcool = hipoglicemia 40% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "F",
														insulina == "F",
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");
	end		
	
		
rule "44: sintomas +diabetico -glicemia +med sulf +insulina = hipoglicemia 80% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F", 
														medicamentosSulfMegHipog == "S",
														insulina == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, HOSPITAL");
	end		
	
		
rule "45: sintomas +diabetico -glicemia +med sulf -insulina +alcool = hipoglicemia 80% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F", 
														medicamentosSulfMegHipog == "S",
														insulina == "F",
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");
	end			
		
		
rule "46: sintomas +diabetico -glicemia +med sulf -insulina +alcool = hipoglicemia 60% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F", 
														medicamentosSulfMegHipog == "S",
														insulina == "F",
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");
	end	
	
			
rule "47: sintomas +diabetico -glicemia -med sulf +med +insulina = hipoglicemia 80% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F", 
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "S",
														insulina == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, HOSPITAL");
	end	
		
rule "48: sintomas +diabetico -glicemia -med sulf +med -insulina +alcool = hipoglicemia 80% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F", 
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "S",
														insulina == "F",
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");
	end			
	
rule "49: sintomas +diabetico -glicemia -med sulf +med -insulina -alcool = hipoglicemia 60% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F", 
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "S",
														insulina == "F",
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");
	end			
	
rule "50: sintomas +diabetico -glicemia -med sulf -med +insulina = hipoglicemia 60% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F", 
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "F",
														insulina == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");
	end			
	
rule "51: sintomas +diabetico -glicemia -med sulf -med -insulina +alcool= hipoglicemia 60% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F", 
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "F",
														insulina == "F",
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");
	end								

rule "52: sintomas +diabetico -glicemia -med sulf -med -insulina -alcool = hipoglicemia 40% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F", 
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "F",
														insulina == "F",
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
								

rule "53: sintomas -diabetico +glicose +glicemia <70 = hipoglicemia 100% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="F", 
														medirGlicemia == "S", 
														resultadoGlicemia < 70
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, HOSPITAL");	
	end									

rule "54: sintomas -diabetico +glicose -glicemia <70 +alcool = inconclusivo 40% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="F", 
														medirGlicemia == "S", 
														resultadoGlicemia > 70,
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	

rule "55: sintomas -diabetico +glicose -glicemia <70 -alcool = inconclusivo 20% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="F", 
														medirGlicemia == "S", 
														resultadoGlicemia > 70,
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
		

rule "56: sintomas -diabetico -glicose -alcool = Inconclusivo 20% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="F", 
														medirGlicemia == "F", 
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	

rule "57: sintomas -diabetico -glicose +alcool = hipoglicemia 40% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipoglicemia",
														diabetico =="F", 
														medirGlicemia == "F", 
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
				

rule "60: alguns sintomas +diabetico +glicose +glicemia <70 = hipoglicemia 100% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia <= 70
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
				

rule "61: alguns sintomas +diabetico +glicemia -resultado <70 +med sulf +insulina = hipoglicemia 68% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "S",
														insulina == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, Hospital");	
	end	
				
rule "62: alguns sintomas +diabetico +glicemia -resultado <70 +med sulf +insulina = hipoglicemia 68% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "S",
														insulina == "F",
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
		
				
rule "63: alguns sintomas +diabetico +glicemia -resultado <70 +med sulf -insulina -alcool = hipoglicemia 48% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S", 
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "S",
														insulina == "F",
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
		
		
			
rule "64: alguns sintomas +diabetico +glicemia -resultado <70 -med sulf +med +insulina = hipoglicemia 68% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S",
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "S",
														insulina == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
		

			
rule "65: alguns sintomas +diabetico +glicemia -resultado <70 -med sulf +med -insulina +alcool = hipoglicemia 68% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S",
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "S",
														insulina == "F",
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
				
			
rule "66: alguns sintomas +diabetico +glicemia -resultado <70 -med sulf +med -insulina -alcool = hipoglicemia 48% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S",
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "S",
														insulina == "F",
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
				
		
rule "67: alguns sintomas +diabetico +glicemia -resultado <70 -med sulf -med +insulina = hipoglicemia 48% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S",
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "F",
														insulina == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
				
	
rule "68: alguns sintomas +diabetico +glicemia -resultado <70 -med sulf -med -insulina +alcool = hipoglicemia 48% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S",
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "F",
														insulina == "F",
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
				
		

rule "69: alguns sintomas +diabetico +glicemia -resultado <70 -med sulf -med -insulina -alcool = hipoglicemia 48% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "S",
														resultadoGlicemia > 70,
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "F",
														insulina == "F",
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
							
	

rule "70: alguns sintomas +diabetico -glicemia +med sulf +insulina = hipoglicemia 68% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F",
														medicamentosSulfMegHipog == "S",
														insulina == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, Hospital");	
	end	
	
	

rule "71: alguns sintomas +diabetico -glicemia +med sulf -insulina +alcool = hipoglicemia 68% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F",
														medicamentosSulfMegHipog == "S",
														insulina == "F",
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
	
	

rule "72: alguns sintomas +diabetico -glicemia +med sulf -insulina -alcool = hipoglicemia 48% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F",
														medicamentosSulfMegHipog == "S",
														insulina == "F",
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
	
	

rule "73: alguns sintomas +diabetico -glicemia -med sulf +med +insulina = hipoglicemia 68% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F",
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "S",
														insulina == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
	
	
rule "74: alguns sintomas +diabetico -glicemia -med sulf +med -insulina +alcool = hipoglicemia 68% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F",
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "S",
														insulina == "F",
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
	

rule "75: alguns sintomas +diabetico -glicemia -med sulf +med -insulina -alcool = hipoglicemia 48% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S",
														medirGlicemia == "F",
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "S",
														insulina == "F",
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
	

rule "76: alguns sintomas +diabetico -glicemia -med sulf +med -insulina -alcool = hipoglicemia 48% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F",
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "F",
														insulina == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
															

rule "77: alguns sintomas +diabetico -glicemia -med sulf -med -insulina +alcool= hipoglicemia 48% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F",
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "F",
														insulina == "F", 
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
															

rule "78: alguns sintomas +diabetico -glicemia -med sulf -med -insulina -alcool= hipoglicemia 28% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="S", 
														medirGlicemia == "F",
														medicamentosSulfMegHipog == "F",
														medicamentosHipoglicemia == "F",
														insulina == "F", 
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
															

rule "79: alguns sintomas -diabetico +glicose +glicemia <70 = hipoglicemia 100% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="F", 
														medirGlicemia == "S",
														resultadoGlicemia < 70
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
															

rule "80: alguns sintomas -diabetico +glicose -glicemia <70 +alcool = hipoglicemia 28% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="F", 
														medirGlicemia == "S",
														resultadoGlicemia > 70,
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
								

rule "81: alguns sintomas -diabetico +glicose -glicemia <70 -alcool = inconclusivo 8% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="F", 
														medirGlicemia == "S",
														resultadoGlicemia > 70,
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
				

rule "82: alguns sintomas -diabetico -glicose -alcool = hipoglicemia 8% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="F", 
														medirGlicemia == "F",
														alcool == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
				

rule "83: alguns sintomas -diabetico -glicose +alcool = hipoglicemia 28% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipoglicemia",
														diabetico =="F", 
														medirGlicemia == "F",
														alcool == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipoglicemia, UPA");	
	end	
		
rule "90: sintomas +diabetivo +potasio +resultado >5,5 = hipercalemia 100% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipercalemia",
														diabetico =="S", 
														medirPotassio == "S",
														resultadopotassio >= 5.5
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipercalemia, Hospital");	
	end	
				

				
rule "91: sintomas +diabetico +potassio -resultado >5,5 +med = hipercalemia 75% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipercalemia",
														diabetico =="S", 
														medirPotassio == "S",
														resultadopotassio < 5.5,
														medicamentosHipercalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipercalemia, UPA");	
	end	
					

rule "92: sintomas +diabetico +potassio -resultado >5,5 -med = inconclusivo 50% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipercalemia",
														diabetico =="S", 
														medirPotassio == "S",
														resultadopotassio < 5.5,
														medicamentosHipercalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
						

rule "93: sintomas +diabetico -potassio +med = hipercalemia 75% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipercalemia",
														diabetico =="S", 
														medirPotassio == "F",
														medicamentosHipercalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipercalemia, UPA");	
	end	
					

rule "94: sintomas +diabetico -potassio -med = inconclusivo 50% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipercalemia",
														diabetico =="S", 
														medirPotassio == "F",
														medicamentosHipercalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
					

rule "95: sintomas -diabetico +potassio >5,5 = hipercalemia 100% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipercalemia",
														diabetico =="F", 
														medirPotassio == "S",
														resultadopotassio > 5.5
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipercalemia, Hospital");	
	end	
					

rule "96: sintomas -diabetico +potassio -resultado >5,5 +med = inconclusivo 50% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipercalemia",
														diabetico =="F", 
														medirPotassio == "S",
														resultadopotassio < 5.5,
														medicamentosHipercalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
					

rule "97: sintomas -diabetico +potassio -resultado >5,5 -med = inconclusivo 25% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipercalemia",
														diabetico =="F", 
														medirPotassio == "S",
														resultadopotassio < 5.5,
														medicamentosHipercalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
								

rule "98: sintomas -diabetico -potassio +med = hipercalemia 50% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipercalemia",
														diabetico =="F", 
														medirPotassio == "F",
														medicamentosHipercalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipercalemia, UPA");	
	end	
												

rule "99: sintomas -diabetico -potassio -med = inconclusivo 25% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipercalemia",
														diabetico =="F", 
														medirPotassio == "F",
														medicamentosHipercalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
												

rule "101: alguns sintomas +diabetico +potassio >5,5 = hipercalemia 100% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipercalemia",
														diabetico =="S", 
														medirPotassio == "S",
														resultadopotassio > 5.5
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipercalemia, Hospital");	
	end	
												
												

rule "102: alguns sintomas +diabetico +potassio ->5,5 +med = inconclusivo 63% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipercalemia",
														diabetico =="S", 
														medirPotassio == "S",
														resultadopotassio < 5.5,
														medicamentosHipercalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
						

rule "103: alguns sintomas +diabetico +potassio ->5,5 -med = inconclusivo 38% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipercalemia",
														diabetico =="S", 
														medirPotassio == "S",
														resultadopotassio < 5.5,
														medicamentosHipercalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
					

rule "104: alguns sintomas +diabetico -potassio +med = hipercalemia 63% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipercalemia",
														diabetico =="S", 
														medirPotassio == "F",
														medicamentosHipercalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipercalemia, UPA");	
	end	
								

rule "105: alguns sintomas +diabetico -potassio -med = inconclusivo 38% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipercalemia",
														diabetico =="S", 
														medirPotassio == "F",
														medicamentosHipercalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
								

rule "106: alguns sintomas -diabetico +potassio ->5,5  = hipercalemia 100% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipercalemia",
														diabetico =="F", 
														medirPotassio == "S",
														resultadopotassio > 5.5
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipercalemia, Hospital");	
	end	
								

rule "107: alguns sintomas -diabetico +potassio ->5,5 +med = inconclusivo 38% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipercalemia",
														diabetico =="F", 
														medirPotassio == "S",
														resultadopotassio < 5.5,
														medicamentosHipercalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
									

rule "108: alguns sintomas -diabetico +potassio ->5,5 -med = inconclusivo 13% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipercalemia",
														diabetico =="F", 
														medirPotassio == "S",
														resultadopotassio < 5.5,
														medicamentosHipercalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
									

rule "109: alguns sintomas -diabetico -potassio +med = inconclusivo 38% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipercalemia",
														diabetico =="F", 
														medirPotassio == "F",
														medicamentosHipercalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
									

rule "110: alguns sintomas -diabetico -potassio -med = inconclusivo 13% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipercalemia",
														diabetico =="F", 
														medirPotassio == "F",
														medicamentosHipercalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
									
						

rule "117: sintomas +diabetivo +potasio +resultado <3,5 = hipocalemia 100% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipocalemia",
														diabetico =="S", 
														medirPotassio == "S",
														resultadopotassio < 3.5
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipocalemia, Hospital");	
	end	
									

rule "118: sintomas +diabetico +potasio -resultado <3,5 +med = hipocalemia 75% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipocalemia",
														diabetico =="S", 
														medirPotassio == "S",
														resultadopotassio > 3.5,
														medicamentosHipocalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipocalemia, UPA");	
	end	
																

rule "119: sintomas +diabetico +potasio -resultado <3,5 -med = inconclusivo 50% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipocalemia",
														diabetico =="S", 
														medirPotassio == "S",
														resultadopotassio > 3.5,
														medicamentosHipocalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
																

rule "120: sintomas +diabetico -potasio +med = hipocalemia 75% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipocalemia",
														diabetico =="S", 
														medirPotassio == "F",
														medicamentosHipocalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipocalemia, UPA");	
	end	
																

rule "121: sintomas +diabetico -potasio -med = hipocalemia 50% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipocalemia",
														diabetico =="S", 
														medirPotassio == "F",
														medicamentosHipocalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipocalemia, UPA");	
	end	
																

rule "122: sintomas -diabetico +potasio +resultado <3,5 = hipocalemia 100% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipocalemia",
														diabetico =="F", 
														medirPotassio == "S",
														resultadopotassio < 3.5
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipocalemia, Hospital");	
	end	
																

rule "123: sintomas -diabetico +potassio -resultado <3,5 +med = hipocalemia 50% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipocalemia",
														diabetico =="F", 
														medirPotassio == "S",
														resultadopotassio > 3.5,
														medicamentosHipocalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipocalemia, UPA");	
	end	
																		

rule "124: sintomas -diabetico +potassio -resultado <3,5 -med = hipocalemia 25% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipocalemia",
														diabetico =="F", 
														medirPotassio == "S",
														resultadopotassio > 3.5,
														medicamentosHipocalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipocalemia, UPA");	
	end	
																		

																								

rule "125: sintomas -diabetico -potassio +med = hipocalemia 50% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipocalemia",
														diabetico =="F", 
														medirPotassio == "F",
														medicamentosHipocalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipocalemia, UPA");	
	end	
																				

rule "126: sintomas -diabetico -potassio -med = inconclusivo 25% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Todos os sintomas Hipocalemia",
														diabetico =="F", 
														medirPotassio == "F",
														medicamentosHipocalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
																				

rule "127: alguns sintomas +diabetico +potassio +resultado <3,5 = hipocalemia 100% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipocalemia",
														diabetico =="S", 
														medirPotassio == "S",
														resultadopotassio < 3.5
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipocalemia, Hospital");	
	end	
																				

rule "128: alguns sintomas +diabetico +potasio -resultado <3,5 +med = inconclusivo 63% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipocalemia",
														diabetico =="S", 
														medirPotassio == "S",
														resultadopotassio > 3.5,
														medicamentosHipocalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
																				

rule "129: alguns sintomas +diabetico +potasio -resultado <3,5 -med = inconclusivo 38% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipocalemia",
														diabetico =="S", 
														medirPotassio == "S",
														resultadopotassio > 3.5,
														medicamentosHipocalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
																				

rule "130: alguns sintomas +diabetico -potasio +med = hipocalemia 63% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipocalemia",
														diabetico =="S", 
														medirPotassio == "F",
														medicamentosHipocalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipocalemia, UPA");	
	end	
																				

rule "131: alguns sintomas +diabetico -potasio -med = hipocalemia 38% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipocalemia",
														diabetico =="S", 
														medirPotassio == "F",
														medicamentosHipocalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipocalemia, UPA");	
	end	
																				

rule "132: alguns sintomas -diabetico +potassio +resultado <3,5 = hipocalemia 100% Hospital"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipocalemia",
														diabetico =="F", 
														medirPotassio == "S",
														resultadopotassio < 3.5
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipocalemia, Hospital");	
	end	
																				

rule "133: alguns sintomas -diabetico +potassio -resultado <3,5 +med = inconclusivo 38% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipocalemia",
														diabetico =="F", 
														medirPotassio == "S",
														resultadopotassio > 3.5,
														medicamentosHipocalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
																				

rule "134: alguns sintomas -diabetico +potassio -resultado <3,5 +med = inconclusivo 13% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipocalemia",
														diabetico =="F", 
														medirPotassio == "S",
														resultadopotassio > 3.5,
														medicamentosHipocalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
																													
																			

rule "135: alguns sintomas -diabetico -potassio +med = hipocalemia 38% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipocalemia",
														diabetico =="F", 
														medirPotassio == "F",
														medicamentosHipocalemia == "S"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Hipocalemia, UPA");	
	end	
																													

rule "136: alguns sintomas -diabetico -potassio +med = inconclusivo 13% UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas == "Alguns sintomas Hipocalemia",
														diabetico =="F", 
														medirPotassio == "F",
														medicamentosHipocalemia == "F"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
																													

rule "inconclusivo UPA"
	when 
		sistemaEspecialistaObject: SistemaEspecialista(
														tipoSintomas != "Todos os sintomas Hipoglicemia",
														tipoSintomas != "Todos os sintomas Hiperglicemia",
														tipoSintomas != "Todos os sintomas Hipocalemia",
														tipoSintomas != "Todos os sintomas Hipercalemia",
														tipoSintomas != "Alguns sintomas Hipoglicemia",
														tipoSintomas != "Alguns sintomas Hiperglicemia",
														tipoSintomas != "Alguns sintomas Hipocalemia",
														tipoSintomas != "Alguns sintomas Hipercalemia"
													 )  
	then
		sistemaEspecialistaObject.setSuspeitaDoenca("Inconclusivo, UPA");	
	end	
																																	
							